// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2019.2
// Copyright (C) 1986-2019 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "cordic.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic cordic::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic cordic::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<3> cordic::ap_ST_fsm_state1 = "1";
const sc_lv<3> cordic::ap_ST_fsm_state2 = "10";
const sc_lv<3> cordic::ap_ST_fsm_state3 = "100";
const sc_lv<32> cordic::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_lv<32> cordic::ap_const_lv32_1 = "1";
const sc_lv<1> cordic::ap_const_lv1_0 = "0";
const sc_lv<32> cordic::ap_const_lv32_2 = "10";
const sc_lv<12> cordic::ap_const_lv12_400 = "10000000000";
const sc_lv<12> cordic::ap_const_lv12_0 = "000000000000";
const sc_lv<12> cordic::ap_const_lv12_26D = "1001101101";
const sc_lv<6> cordic::ap_const_lv6_0 = "000000";
const sc_lv<1> cordic::ap_const_lv1_1 = "1";
const sc_lv<32> cordic::ap_const_lv32_B = "1011";
const sc_lv<6> cordic::ap_const_lv6_20 = "100000";
const sc_lv<6> cordic::ap_const_lv6_1 = "1";
const sc_lv<13> cordic::ap_const_lv13_0 = "0000000000000";
const sc_lv<32> cordic::ap_const_lv32_A = "1010";
const sc_lv<32> cordic::ap_const_lv32_15 = "10101";
const bool cordic::ap_const_boolean_1 = true;

cordic::cordic(sc_module_name name) : sc_module(name), mVcdFile(0) {
    cordic_mul_mul_13bkb_U1 = new cordic_mul_mul_13bkb<1,1,13,12,22>("cordic_mul_mul_13bkb_U1");
    cordic_mul_mul_13bkb_U1->din0(r_V_fu_150_p3);
    cordic_mul_mul_13bkb_U1->din1(r_V_5_fu_228_p1);
    cordic_mul_mul_13bkb_U1->dout(r_V_5_fu_228_p2);
    cordic_mul_mul_13bkb_U2 = new cordic_mul_mul_13bkb<1,1,13,12,22>("cordic_mul_mul_13bkb_U2");
    cordic_mul_mul_13bkb_U2->din0(r_V_2_fu_184_p3);
    cordic_mul_mul_13bkb_U2->din1(r_V_6_fu_235_p1);
    cordic_mul_mul_13bkb_U2->dout(r_V_6_fu_235_p2);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln18_fu_128_p2 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln18_fu_128_p2 );

    SC_METHOD(thread_c_V);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln18_fu_128_p2 );
    sensitive << ( p_Val2_2_reg_96 );

    SC_METHOD(thread_c_V_ap_vld);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln18_fu_128_p2 );

    SC_METHOD(thread_current_cos_V_fu_218_p2);
    sensitive << ( sin_shift_V_reg_261 );
    sensitive << ( p_Val2_2_reg_96 );

    SC_METHOD(thread_current_sin_V_fu_223_p2);
    sensitive << ( cos_shift_V_reg_256 );
    sensitive << ( p_Val2_4_reg_83 );

    SC_METHOD(thread_icmp_ln18_fu_128_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( j_0_reg_109 );

    SC_METHOD(thread_j_fu_134_p2);
    sensitive << ( j_0_reg_109 );

    SC_METHOD(thread_r_V_2_fu_184_p3);
    sensitive << ( tmp_reg_242 );
    sensitive << ( sext_ln1116_2_fu_174_p1 );
    sensitive << ( sub_ln1118_1_fu_178_p2 );

    SC_METHOD(thread_r_V_5_fu_228_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sext_ln1118_fu_161_p1 );

    SC_METHOD(thread_r_V_6_fu_235_p1);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( sext_ln1118_fu_161_p1 );

    SC_METHOD(thread_r_V_7_fu_214_p1);
    sensitive << ( trunc_ln_fu_204_p4 );

    SC_METHOD(thread_r_V_fu_150_p3);
    sensitive << ( tmp_reg_242 );
    sensitive << ( sext_ln1116_fu_140_p1 );
    sensitive << ( sub_ln1118_fu_144_p2 );

    SC_METHOD(thread_s_V);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln18_fu_128_p2 );
    sensitive << ( p_Val2_4_reg_83 );

    SC_METHOD(thread_s_V_ap_vld);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln18_fu_128_p2 );

    SC_METHOD(thread_sext_ln1116_2_fu_174_p1);
    sensitive << ( p_Val2_4_reg_83 );

    SC_METHOD(thread_sext_ln1116_fu_140_p1);
    sensitive << ( p_Val2_2_reg_96 );

    SC_METHOD(thread_sext_ln1118_fu_161_p1);
    sensitive << ( factor_0_reg_72 );

    SC_METHOD(thread_sub_ln1118_1_fu_178_p2);
    sensitive << ( sext_ln1116_2_fu_174_p1 );

    SC_METHOD(thread_sub_ln1118_fu_144_p2);
    sensitive << ( sext_ln1116_fu_140_p1 );

    SC_METHOD(thread_trunc_ln_fu_204_p4);
    sensitive << ( factor_0_reg_72 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln18_fu_128_p2 );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    ap_CS_fsm = "001";
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "cordic_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, theta_V, "(port)theta_V");
    sc_trace(mVcdFile, s_V, "(port)s_V");
    sc_trace(mVcdFile, s_V_ap_vld, "(port)s_V_ap_vld");
    sc_trace(mVcdFile, c_V, "(port)c_V");
    sc_trace(mVcdFile, c_V_ap_vld, "(port)c_V_ap_vld");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, tmp_reg_242, "tmp_reg_242");
    sc_trace(mVcdFile, j_fu_134_p2, "j_fu_134_p2");
    sc_trace(mVcdFile, j_reg_251, "j_reg_251");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, cos_shift_V_reg_256, "cos_shift_V_reg_256");
    sc_trace(mVcdFile, icmp_ln18_fu_128_p2, "icmp_ln18_fu_128_p2");
    sc_trace(mVcdFile, sin_shift_V_reg_261, "sin_shift_V_reg_261");
    sc_trace(mVcdFile, r_V_7_fu_214_p1, "r_V_7_fu_214_p1");
    sc_trace(mVcdFile, r_V_7_reg_266, "r_V_7_reg_266");
    sc_trace(mVcdFile, current_cos_V_fu_218_p2, "current_cos_V_fu_218_p2");
    sc_trace(mVcdFile, ap_CS_fsm_state3, "ap_CS_fsm_state3");
    sc_trace(mVcdFile, current_sin_V_fu_223_p2, "current_sin_V_fu_223_p2");
    sc_trace(mVcdFile, factor_0_reg_72, "factor_0_reg_72");
    sc_trace(mVcdFile, p_Val2_4_reg_83, "p_Val2_4_reg_83");
    sc_trace(mVcdFile, p_Val2_2_reg_96, "p_Val2_2_reg_96");
    sc_trace(mVcdFile, j_0_reg_109, "j_0_reg_109");
    sc_trace(mVcdFile, sext_ln1116_fu_140_p1, "sext_ln1116_fu_140_p1");
    sc_trace(mVcdFile, sub_ln1118_fu_144_p2, "sub_ln1118_fu_144_p2");
    sc_trace(mVcdFile, r_V_fu_150_p3, "r_V_fu_150_p3");
    sc_trace(mVcdFile, r_V_5_fu_228_p2, "r_V_5_fu_228_p2");
    sc_trace(mVcdFile, sext_ln1116_2_fu_174_p1, "sext_ln1116_2_fu_174_p1");
    sc_trace(mVcdFile, sub_ln1118_1_fu_178_p2, "sub_ln1118_1_fu_178_p2");
    sc_trace(mVcdFile, r_V_2_fu_184_p3, "r_V_2_fu_184_p3");
    sc_trace(mVcdFile, r_V_6_fu_235_p2, "r_V_6_fu_235_p2");
    sc_trace(mVcdFile, trunc_ln_fu_204_p4, "trunc_ln_fu_204_p4");
    sc_trace(mVcdFile, r_V_5_fu_228_p1, "r_V_5_fu_228_p1");
    sc_trace(mVcdFile, sext_ln1118_fu_161_p1, "sext_ln1118_fu_161_p1");
    sc_trace(mVcdFile, r_V_6_fu_235_p1, "r_V_6_fu_235_p1");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
#endif

    }
    mHdltvinHandle.open("cordic.hdltvin.dat");
    mHdltvoutHandle.open("cordic.hdltvout.dat");
}

cordic::~cordic() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete cordic_mul_mul_13bkb_U1;
    delete cordic_mul_mul_13bkb_U2;
}

void cordic::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        factor_0_reg_72 = r_V_7_reg_266.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        factor_0_reg_72 = ap_const_lv12_400;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        j_0_reg_109 = j_reg_251.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        j_0_reg_109 = ap_const_lv6_0;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_Val2_2_reg_96 = current_cos_V_fu_218_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_Val2_2_reg_96 = ap_const_lv12_26D;
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state3.read())) {
        p_Val2_4_reg_83 = current_sin_V_fu_223_p2.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        p_Val2_4_reg_83 = ap_const_lv12_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln18_fu_128_p2.read(), ap_const_lv1_0))) {
        cos_shift_V_reg_256 = r_V_5_fu_228_p2.read().range(21, 10);
        r_V_7_reg_266 = r_V_7_fu_214_p1.read();
        sin_shift_V_reg_261 = r_V_6_fu_235_p2.read().range(21, 10);
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        j_reg_251 = j_fu_134_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        tmp_reg_242 = theta_V.read().range(11, 11);
    }
}

void cordic::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void cordic::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void cordic::thread_ap_CS_fsm_state3() {
    ap_CS_fsm_state3 = ap_CS_fsm.read()[2];
}

void cordic::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln18_fu_128_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void cordic::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void cordic::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln18_fu_128_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void cordic::thread_c_V() {
    c_V = p_Val2_2_reg_96.read();
}

void cordic::thread_c_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln18_fu_128_p2.read(), ap_const_lv1_1))) {
        c_V_ap_vld = ap_const_logic_1;
    } else {
        c_V_ap_vld = ap_const_logic_0;
    }
}

void cordic::thread_current_cos_V_fu_218_p2() {
    current_cos_V_fu_218_p2 = (!p_Val2_2_reg_96.read().is_01() || !sin_shift_V_reg_261.read().is_01())? sc_lv<12>(): (sc_bigint<12>(p_Val2_2_reg_96.read()) - sc_biguint<12>(sin_shift_V_reg_261.read()));
}

void cordic::thread_current_sin_V_fu_223_p2() {
    current_sin_V_fu_223_p2 = (!cos_shift_V_reg_256.read().is_01() || !p_Val2_4_reg_83.read().is_01())? sc_lv<12>(): (sc_biguint<12>(cos_shift_V_reg_256.read()) + sc_bigint<12>(p_Val2_4_reg_83.read()));
}

void cordic::thread_icmp_ln18_fu_128_p2() {
    icmp_ln18_fu_128_p2 = (!j_0_reg_109.read().is_01() || !ap_const_lv6_20.is_01())? sc_lv<1>(): sc_lv<1>(j_0_reg_109.read() == ap_const_lv6_20);
}

void cordic::thread_j_fu_134_p2() {
    j_fu_134_p2 = (!j_0_reg_109.read().is_01() || !ap_const_lv6_1.is_01())? sc_lv<6>(): (sc_biguint<6>(j_0_reg_109.read()) + sc_biguint<6>(ap_const_lv6_1));
}

void cordic::thread_r_V_2_fu_184_p3() {
    r_V_2_fu_184_p3 = (!tmp_reg_242.read()[0].is_01())? sc_lv<13>(): ((tmp_reg_242.read()[0].to_bool())? sub_ln1118_1_fu_178_p2.read(): sext_ln1116_2_fu_174_p1.read());
}

void cordic::thread_r_V_5_fu_228_p1() {
    r_V_5_fu_228_p1 =  (sc_lv<12>) (sext_ln1118_fu_161_p1.read());
}

void cordic::thread_r_V_6_fu_235_p1() {
    r_V_6_fu_235_p1 =  (sc_lv<12>) (sext_ln1118_fu_161_p1.read());
}

void cordic::thread_r_V_7_fu_214_p1() {
    r_V_7_fu_214_p1 = esl_sext<12,11>(trunc_ln_fu_204_p4.read());
}

void cordic::thread_r_V_fu_150_p3() {
    r_V_fu_150_p3 = (!tmp_reg_242.read()[0].is_01())? sc_lv<13>(): ((tmp_reg_242.read()[0].to_bool())? sub_ln1118_fu_144_p2.read(): sext_ln1116_fu_140_p1.read());
}

void cordic::thread_s_V() {
    s_V = p_Val2_4_reg_83.read();
}

void cordic::thread_s_V_ap_vld() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln18_fu_128_p2.read(), ap_const_lv1_1))) {
        s_V_ap_vld = ap_const_logic_1;
    } else {
        s_V_ap_vld = ap_const_logic_0;
    }
}

void cordic::thread_sext_ln1116_2_fu_174_p1() {
    sext_ln1116_2_fu_174_p1 = esl_sext<13,12>(p_Val2_4_reg_83.read());
}

void cordic::thread_sext_ln1116_fu_140_p1() {
    sext_ln1116_fu_140_p1 = esl_sext<13,12>(p_Val2_2_reg_96.read());
}

void cordic::thread_sext_ln1118_fu_161_p1() {
    sext_ln1118_fu_161_p1 = esl_sext<22,12>(factor_0_reg_72.read());
}

void cordic::thread_sub_ln1118_1_fu_178_p2() {
    sub_ln1118_1_fu_178_p2 = (!ap_const_lv13_0.is_01() || !sext_ln1116_2_fu_174_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(sext_ln1116_2_fu_174_p1.read()));
}

void cordic::thread_sub_ln1118_fu_144_p2() {
    sub_ln1118_fu_144_p2 = (!ap_const_lv13_0.is_01() || !sext_ln1116_fu_140_p1.read().is_01())? sc_lv<13>(): (sc_biguint<13>(ap_const_lv13_0) - sc_bigint<13>(sext_ln1116_fu_140_p1.read()));
}

void cordic::thread_trunc_ln_fu_204_p4() {
    trunc_ln_fu_204_p4 = factor_0_reg_72.read().range(11, 1);
}

void cordic::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln18_fu_128_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        default : 
            ap_NS_fsm = "XXX";
            break;
    }
}

void cordic::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"theta_V\" :  \"" << theta_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_V\" :  \"" << s_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"s_V_ap_vld\" :  \"" << s_V_ap_vld.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"c_V\" :  \"" << c_V.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"c_V_ap_vld\" :  \"" << c_V_ap_vld.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

